### ISSUE TITLE
backend api for notes crud operations

### ISSUE THREAD

**Issue by VinayV9** [UdacityMobileWebScholarship/just-notes#13]
Tasks to be done:

- Backend bootstrapped with express and mongodb as database setup
- Mongoose model for notes
- API for create/update/delete/edit a note.
- Socket.io setup for realtime saving of notes.

**Comment by skyshader** [comment]
@VinayV9 1st one is already taken. 2nd and 3rd are remaining. You can take those. If someone else is interested in contributing, do share the tasks with them. Cheers :)

**Comment by sounak07** [comment]
I have taken task 1.

**Comment by VinayV9** [comment]
ok

**Comment by anurag-majumdar** [comment]
I want to work on task #3. @skyshader

**Comment by skyshader** [comment]
@VinayV9 which tasks did you choose, can you clarify? So that I can let @anurag-majumdar pick one from the above list.

**Comment by VinayV9** [comment]
API part

**Comment by anurag-majumdar** [comment]
Thanks @skyshader . Let's decide which areas we will work on. Is the schema ready to be updated? If not I can also help setup the schema.

**Comment by skyshader** [comment]
@anurag-majumdar let's start that discussion here: #15 :)

**Comment by skarthikeyan96** [comment]
Any tasks that I can help with @skyshader

**Comment by skyshader** [comment]
@skarthikeyan96 let's talk about this in our slack channel. :)

**Comment by highskillzz** [comment]
@skyshader any tasks I can help with?

**Comment by vipinkhushu** [comment]
Hi @skyshader ,
Is there any nodejs, mongodb , express tasks? I am interested.

**Comment by sb7896** [comment]
I like to work on socket.io setup part. Is it taken?

**Comment by Nagendra1421** [comment]
No, You can contribute in any functionality whether it is frontend side or backend side, you can also help in contributing in database schemas. Everyone are welcomed to work and collaborate to learn and build this app.

**Comment by sb7896** [comment]
@Nagendra1421 Who is working on which part? So that I can collaborate with them.

**Comment by Nagendra1421** [comment]
Actually Me and skyshader are working on backend sides, if you wanna work on socket.io side you can work on it. Let's work together

**Comment by sb7896** [comment]
Yeah sure, let me know if I can help on any part.

**Comment by vipinkhushu** [comment]
@Nagendra1421 Can you share details on which particular part are you guys working? i want to contribute

**Comment by sounak07** [comment]
I also want to on some socket.io or delete, update routes if assigned.
@Nagendra1421 @skyshader

**Comment by Nagendra1421** [comment]
Sure Sounak we'll let you know on slack channel.

**Comment by sounak07** [comment]
Ok please let me know

**Comment by Abdulkadir98** [comment]
I would love to contribute to the backend routes as well! Has the userSchema been taken? if not I would like to do that

**Comment by VinayV9** [comment]
task 1 completed backend bootstrap
task 2 completed schema
task 3 completed crud api
only task 4 is pending

**Comment by Nagendra1421** [comment]
Anyone interested in working on adding crud functionality?

**Comment by highskillzz** [comment]
What routes are rewuired

**Comment by VinayV9** [comment]
yes @Nagendra1421

**Comment by VinayV9** [comment]
@Nagendra1421 i added crud functionality i submitted pr on it which is still pending . are talking about socket.io
