### ISSUE TITLE
schema for notes

### ISSUE THREAD

**Issue by VinayV9** [UdacityMobileWebScholarship/just-notes#15]
what should be the data parameteres

**Comment by VinayV9** [comment]
please keep update this schema

notes = {
 "noteId": string,
 "note":string,
"date": date,
}

**Comment by sounak07** [comment]
We need an note title as well

**Comment by VinayV9** [comment]
ok

**Comment by skyshader** [comment]
Let's add `created_at`, `updated_at` and `is_deleted` to keep track of when the note was created, last updated and if it is deleted.

**Comment by VinayV9** [comment]
any name conventions to the schema??

**Comment by anurag-majumdar** [comment]
Okay, so the final schema will look like this:

notesSchema = {
"slug": string,
"title":string,
"description":string,
"created_at": date,
"updated_at":date,
"is_deleted": boolean
}

So we will be using this schema for CRUD operations via RESTful requests to the client?

**Comment by Asim1996** [comment]
Would we have a user schema too right? and then a creator property in notesSchema.

**Comment by skyshader** [comment]
No, we won't be having anything related to users as of now. Just save and share notes using a unique link. :) Later we can add user and authenticate him to save his notes to the database. Currently we will store all his notes on his browser using IndexedDB we learned in the course :)

**Comment by anurag-majumdar** [comment]
@skyshader Well said bro. I am thinking of taking up the following routes:
POST /notes
GET /notes

**Comment by anurag-majumdar** [comment]
I have made the respective changes by adding a PR for index and create note routes.
